### ISSUE TITLE
routing

### ISSUE THREAD

**Issue by mekdes-112** [mekdes-112/food-recipe-web#1]
had a problem with routing

**Comment by micahea** [comment]
first, change this on main.js 

import Vue from 'vue'
import App from './App.vue'
import router from './router'

Vue.config.productionTip = false

new Vue({
    router,
    render: h => h(App),
}).$mount('#app')


in to this


import App from './App.vue'
import router from './router'
import { createApp } from 'vue'

createApp(App).use(router).mount('#app')

then fix routing on router.js
add  createRouter on import  from vue- router 

import {createRouter, createWebHistory } from 'vue-router';

then create route array to register all routes 

const routes = [
        { path: '/', component: HomePage },
        { path: '/login', component: LoginForm },
        { path: '/register', component: RegisterForm }
    ]

const router = createRouter({
    history: createWebHistory(),
    routes
})
 export default router

this will work I hope

**Comment by mekdes-112** [comment]
Thank you micahea it worked
